# Generated by Django 6.0.4 on 2026-05-20 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ad Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Short description about the ad')),
                ('prompt', models.TextField(help_text='Full prompt used to create this ad')),
                ('video', models.FileField(help_text='Upload ad video (MP4)', upload_to='ads/videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ads/thumbnails/%Y/%m/')),
                ('copy_count', models.IntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.adcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='ads', to='ads.adtag')),
            ],
            options={
                'ordering': ['-is_trending', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-is_trending', '-created_at'], name='ads_ad_is_tren_b8644e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedad',
            unique_together={('user', 'ad')},
        ),
    ]
