# Generated by Django 6.0.4 on 2026-04-27 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='The actual AI prompt text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prompts/%Y/%m/')),
                ('copy_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if image was generated via AI API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompts.tag')),
            ],
            options={
                'ordering': ['-is_trending', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'prompt')},
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-is_trending', '-created_at'], name='prompts_pro_is_tren_05a459_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['category'], name='prompts_pro_categor_80711f_idx'),
        ),
    ]
